name: Cypress

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Fonts
        run: sudo apt install fonts-noto-jp
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          # https://github.com/cypress-io/github-action#component-tests
          component: true
          browser: chrome
      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-snapshots
          path: cypress/snapshots
